/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ContinentsIndexImport } from './routes/continents.index'
import { Route as ContinentsContinentImport } from './routes/continents.$continent'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ContinentsIndexRoute = ContinentsIndexImport.update({
  path: '/continents/',
  getParentRoute: () => rootRoute,
} as any)

const ContinentsContinentRoute = ContinentsContinentImport.update({
  path: '/continents/$continent',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/continents/$continent': {
      id: '/continents/$continent'
      path: '/continents/$continent'
      fullPath: '/continents/$continent'
      preLoaderRoute: typeof ContinentsContinentImport
      parentRoute: typeof rootRoute
    }
    '/continents/': {
      id: '/continents/'
      path: '/continents'
      fullPath: '/continents'
      preLoaderRoute: typeof ContinentsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/continents/$continent': typeof ContinentsContinentRoute
  '/continents': typeof ContinentsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/continents/$continent': typeof ContinentsContinentRoute
  '/continents': typeof ContinentsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/continents/$continent': typeof ContinentsContinentRoute
  '/continents/': typeof ContinentsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/continents/$continent' | '/continents'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/continents/$continent' | '/continents'
  id: '__root__' | '/' | '/continents/$continent' | '/continents/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContinentsContinentRoute: typeof ContinentsContinentRoute
  ContinentsIndexRoute: typeof ContinentsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContinentsContinentRoute: ContinentsContinentRoute,
  ContinentsIndexRoute: ContinentsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/continents/$continent",
        "/continents/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/continents/$continent": {
      "filePath": "continents.$continent.tsx"
    },
    "/continents/": {
      "filePath": "continents.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
